### ISSUE TITLE
Ability to exclude certain files or directories

### ISSUE THREAD

**Issue by nmoinvaz** [harupy/find-trailing-whitespace#17]
It would be great to be able to exclude a list of files or directories from being checked. Right now the linter currently checks certain files that are only used for testing.

**Comment by mathstuf** [comment]
IMO, using the existing Git attribute [`whitespace`](https://www.git-scm.com/docs/gitattributes#_whitespace) to store this information sounds far better than some custom configuration to me.

**Comment by nmoinvaz** [comment]
I no longer need this. I just implemented something a bit simpler for my needs: https://github.com/zlib-ng/zlib-ng/blob/develop/.github/workflows/lint.yml.
